(() => {
  const catalogUrl = localStorage.getItem('cca:catalog-url') || 'http://localhost:4002';
  const state = JSON.parse(localStorage.getItem('cca:merchant-dashboard:v1') || 'null') || { type:'sme', products:[], integration:null, imported:false, profile:true, permissions:{ discovery:true,recommendations:true,inventory:true,price:true,cart:true,checkout:false,orders:false }, activity:['Set up your merchant workspace'] };
  const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
  const save = () => localStorage.setItem('cca:merchant-dashboard:v1', JSON.stringify(state));
  const addActivity = x => { state.activity.unshift(x); state.activity=state.activity.slice(0,5); save(); render(); };
  function score(){ let n=state.profile?1:0; n+=state.imported?3:0; n+=state.integration?1:0; n+=state.permissions.discovery&&state.permissions.inventory&&state.permissions.price?1:0; return Math.round(n/6*100); }
  function render(){ const pct=score(), products=state.products, compatible=products.filter(p=>p.name&&p.price!==''&&p.currency&&p.category&&p.description&&p.availability!==undefined).length; $('#score').textContent=pct+'%'; $('#ring').style.setProperty('--p',pct); $('#ready-status').innerHTML=pct===100?'<span class="dot"></span><span>Agent Ready</span>':'<span class="dot"></span><span>Getting agent ready</span>'; $('#product-count').textContent=products.length; $('#validity').textContent=products.length?`${compatible}/${products.length}`:'—'; $('#integration-count').textContent=state.integration?1:0; $('#permission-count').textContent=Object.values(state.permissions).filter(Boolean).length+'/7'; $('#type-tag').textContent=({sme:'SME setup',growing:'Growing business',enterprise:'Enterprise setup'})[state.type]; $('#checklist').innerHTML=[['Merchant profile configured',state.profile],['Product catalog connected',state.imported],['Product information complete',state.imported&&compatible===products.length],['Inventory information available',products.length&&products.every(p=>p.stock!==''||p.availability!==undefined)],['API integration / agent access configured',!!state.integration],['Checkout integration configured',state.permissions.checkout]].map(([t,ok])=>`<div class="check ${ok?'ok':'wait'}">${t}</div>`).join(''); $('#activity').innerHTML=state.activity.map((x,i)=>`<li><span>${x}</span><small>${i?'Earlier':'Just now'}</small></li>`).join(''); $('#permissions').innerHTML=[['discovery','Product discovery','Allow agents to discover products.'],['recommendations','Product recommendations','Allow agents to recommend products to shoppers.'],['inventory','Inventory lookup','Allow agents to check current availability.'],['price','Price lookup','Allow agents to retrieve current prices.'],['cart','Cart creation','Allow agents to create shopping carts.'],['checkout','Checkout','Allow agents to initiate checkout.'],['orders','Order placement','Allow agents to place orders.']].map(([id,title,desc])=>`<div class="permission row"><div><b>${title}</b><p>${desc}</p></div><label class="toggle"><input data-permission="${id}" type="checkbox" ${state.permissions[id]?'checked':''}><span class="slider"></span></label></div>`).join(''); }
  function switchView(view){ $$('.view').forEach(x=>x.classList.toggle('active',x.id===view)); $$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===view)); $('#page-title').textContent=({overview:'Welcome back, Sole & Stride',catalog:'Catalog onboarding',integrations:'Integrations',settings:'Agent settings',profile:'Store profile',orders:'Orders',analytics:'Analytics'})[view]; }
  $$('nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view)); $$('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));
  $$('#types input').forEach(input=>input.onchange=e=>{state.type=e.target.value; $$('#types .choice').forEach(x=>x.classList.toggle('selected',x.querySelector('input').checked)); $('#api-config').classList.toggle('hidden',state.type!=='enterprise'); $('#no-code').classList.toggle('hidden',state.type==='enterprise'); addActivity(`Selected ${e.target.closest('.choice').querySelector('h3').textContent} setup`);});
  $('#platforms').onclick=e=>{const b=e.target.closest('button');if(!b)return; $$('#platforms button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.integration=b.dataset.platform; $('#connect-note').className='notice'; $('#connect-note').textContent=`${state.integration} selected. This is a demo connection — no third-party account has been authorised.`;addActivity(`Selected ${state.integration} integration`);};
  $('#test-connection').onclick=()=>{const r=$('#connection-result');r.className='notice';r.textContent='✓ Connection successful — simulated test completed. Save credentials in your secure production integration service.';state.integration='API integration';addActivity('Tested API integration successfully');};
  $('#permissions').onchange=e=>{if(!e.target.dataset.permission)return; const key=e.target.dataset.permission;if(key==='orders'&&e.target.checked&&!confirm('Enable agent order placement? Agents could create orders through your connected workflow.')){e.target.checked=false;return;}state.permissions[key]=e.target.checked;addActivity(`${e.target.checked?'Enabled':'Disabled'} ${e.target.closest('.permission').querySelector('b').textContent}`);};
  $('#save-profile').onclick=()=>{state.profile=Boolean($('#store-name').value.trim());$('#profile-result').classList.remove('hidden');addActivity('Updated store profile');};
  const sample=`product_id,name,description,price,currency,category,image_url,sku,stock_quantity,availability,size,color\nshoe_001,Cloud Runner,Lightweight everyday running shoe,129.99,USD,fashion,https://picsum.photos/seed/cloudrunner/400/300,CR-001,12,true,8|9|10,navy|white\nshoe_002,Trail Peak,Weather-ready trail shoe,159.00,USD,fashion,https://picsum.photos/seed/trailpeak/400/300,TP-002,0,false,9|10|11,green\nshoe_003,Weekend Slide,,39.00,USD,fashion,,WS-003,20,true,7|8|9,black`;
  function parse(text){const lines=text.trim().split(/\r?\n/); if(lines.length<2) return {products:[],errors:['Your CSV needs a header row and at least one product.']};const split=l=>{let a=[],q=false,c='';for(const x of l){if(x==='"')q=!q;else if(x===','&&!q){a.push(c.trim());c=''}else c+=x}a.push(c.trim());return a.map(x=>x.replace(/^"|"$/g,''))};const h=split(lines[0]).map(x=>x.toLowerCase());const required=['name','price','currency','category'];let errors=[],products=[];lines.slice(1).forEach((l,i)=>{let row=Object.fromEntries(h.map((k,j)=>[k,split(l)[j]??'']));let miss=required.filter(k=>!row[k]);if(miss.length||isNaN(Number(row.price)))errors.push(`Row ${i+2}: ${miss.length?`missing ${miss.join(', ')}`:'price must be numeric'}`);else products.push({...row,availability:['true','yes','1','available'].includes(row.availability.toLowerCase()),stock:row.stock_quantity});});return {products,errors};}
  function preview(result){state.pending=result.products; const total=result.products.length+result.errors.length; $('#preview-sub').textContent= total?`${total} products detected · ${result.products.length} valid · ${result.errors.length} require attention`:'No products detected.'; $('#preview').innerHTML=[...result.products.slice(0,6).map(p=>`<tr><td><b>${p.name}</b><br><small>${p.sku||p.product_id||'No SKU'}</small></td><td>${p.currency} ${p.price}</td><td>${p.category}</td><td><span class="badge">Valid</span></td></tr>`),...result.errors.map(e=>`<tr><td colspan="3">${e}</td><td><span class="badge warn">Fix needed</span></td></tr>`)].join('')||'<tr><td colspan="4">No valid products detected.</td></tr>'; $('#confirm').classList.toggle('hidden',!result.products.length); $('#s1').className='step done';$('#s2').className='step current'; }
  function load(file){const reader=new FileReader();reader.onload=()=>{const r=parse(reader.result);preview(r);$('#catalog-result').innerHTML=r.errors.length?`<div class="notice error">${r.errors.length} row${r.errors.length>1?'s':''} need attention. You can still import valid products.</div>`:`<div class="notice">✓ Your catalog is ready to import.</div>`};reader.readAsText(file);}
  $('#choose').onclick=()=>$('#file').click();$('#file').onchange=e=>e.target.files[0]&&load(e.target.files[0]); const drop=$('#drop');['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('over')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('over')}));drop.ondrop=e=>e.dataTransfer.files[0]&&load(e.dataTransfer.files[0]); $('#sample').onclick=()=>preview(parse(sample)); $('#download').onclick=()=>{const a=document.createElement('a');a.href='data:text/csv;charset=utf-8,'+encodeURIComponent('product_id,name,description,price,currency,category,image_url,sku,stock_quantity,availability,size,color\n');a.download='catalog-template.csv';a.click();};
  $('#confirm').onclick=async()=>{const products=state.pending||[];const button=$('#confirm');button.disabled=true;button.textContent='Importing…';try{const csv=['product_id,name,description,price,currency,category,image_url,availability',...products.map(p=>[p.product_id,p.name,p.description,p.price,p.currency,p.category,p.image_url,p.availability].map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(','))].join('\n'); const res=await fetch(`${catalogUrl}/merchants/merchant_123/products/csv`,{method:'POST',headers:{'content-type':'text/csv'},body:csv});if(!res.ok)throw Error();}catch{ /* Catalog service optional in the static prototype; state remains locally usable. */ }finally{state.products=products;state.imported=true;state.pending=null;save();$('#s2').className='step done';$('#s3').className='step done';$('#catalog-result').innerHTML='<div class="notice">✓ Catalog imported. Products are now available to the connected shopping agent when the catalog service is running.</div>';button.classList.add('hidden');addActivity(`Imported ${products.length} products to catalog`);}}
  render();
})();
