/* Drop-in widget: <script src=".../widget.js" data-merchant="merchant_123" data-agent-url="http://localhost:4000"></script> */
(() => {
  const script = document.currentScript, merchant = script?.dataset.merchant;
  if (!merchant) return console.error("[cca] widget requires data-merchant");
  const base = (script.dataset.agentUrl || "http://localhost:4000").replace(/\/$/, "");
  const key = `cca:widget:v1:${base}:${merchant}`, cash = new Intl.NumberFormat(undefined, { style: "currency", currency: script.dataset.currency || "USD" });
  const id = () => crypto.randomUUID?.() || `s_${Date.now()}_${Math.random().toString(36).slice(2)}`;
  let state; try { state = JSON.parse(localStorage.getItem(key)); } catch {};
  state = state?.sessionId ? state : { sessionId: id(), messages: [] };
  const host = document.createElement("div"); script.insertAdjacentElement("afterend", host);
  const root = host.attachShadow({ mode: "open" });
  root.innerHTML = `<style>*{box-sizing:border-box}.chat{width:min(100%,420px);height:590px;display:flex;flex-direction:column;border:1px solid #d9dce5;border-radius:16px;overflow:hidden;background:#fff;color:#172033;font:14px/1.4 system-ui}header{padding:15px 18px;background:#172a4d;color:#fff;font-weight:700}.thread{flex:1;overflow:auto;padding:15px;background:#f7f8fb}.message,.card{margin:0 0 10px;padding:10px 12px;border-radius:12px;background:#fff;box-shadow:0 1px 2px #0001}.user{margin-left:auto;background:#dceaff}.carousel{display:flex;gap:10px;overflow:auto}.product{flex:0 0 180px;padding:0;overflow:hidden}.product img,.fallback{width:100%;height:110px;object-fit:cover;background:#e9edf5}.fallback{padding:35px;text-align:center;font-size:28px}.body{padding:10px}.name{min-height:38px;font-weight:700}.price{margin:6px 0;color:#385a97;font-weight:700}button{border:0;border-radius:8px;padding:8px 10px;background:#2359b8;color:#fff;font:inherit;font-weight:700;cursor:pointer}.secondary{background:#e8edf7;color:#27364f}button:disabled{opacity:.55}.line{display:flex;justify-content:space-between;gap:8px;margin:5px 0}.total{border-top:1px solid #dde2eb;padding-top:8px;font-weight:800}input{width:100%;padding:8px;border:1px solid #b9c3d4;border-radius:7px;font:inherit}.actions,form{display:flex;gap:8px}.actions{margin-top:12px}form{padding:12px;border-top:1px solid #e4e7ee}form button{flex:none}.notice{padding:8px;margin:8px 0;border-radius:7px;background:#fff4d8}.success{background:#e1f5e7}.error{background:#fde8e8}</style><section class=chat><header>Shopping assistant</header><main class=thread aria-live=polite></main><form><input placeholder="Ask about products…" aria-label=Message><button>Send</button></form></section>`;
  const thread = root.querySelector(".thread"), form = root.querySelector("form"), input = root.querySelector("input");
  const el = (tag, cls, text) => { const n = document.createElement(tag); n.className = cls || ""; if (text != null) n.textContent = text; return n; };
  const save = () => localStorage.setItem(key, JSON.stringify(state)); const scroll = () => thread.scrollTop = thread.scrollHeight;
  const notice = (text, type = "") => { thread.append(el("div", `notice ${type}`, text)); scroll(); };
  async function api(path, body) { const r = await fetch(base + path, { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify(body) }), j = await r.json().catch(() => ({})); if (!r.ok) throw Error(j.error?.message || `Request failed (${r.status})`); return j; }
  async function chat(message) { form.querySelector("button").disabled = true; try { const r = await api("/chat", {session_id:state.sessionId, merchant_id:merchant, message}); r.messages.forEach(item => { state.messages.push({sender:"agent",item}); draw(item); }); save(); } catch(e) { notice(e.message,"error"); } finally { form.querySelector("button").disabled=false; } }
  function preview(p) { const c=el("section","card"); c.append(el("h3","",`Checkout with ${p.merchant_name}`)); p.items.forEach(i=>{const r=el("div","line");r.append(el("span","",`${i.qty} × ${i.name}`),el("span","",cash.format(i.qty*i.price)));c.append(r)}); [["Subtotal",p.subtotal],["Tax",p.tax],["Total",p.total]].forEach(([a,b], x)=>{const r=el("div",x===2?"line total":"line");r.append(el("span","",a),el("span","",cash.format(b)));c.append(r)}); const card=document.createElement("input");card.placeholder="Card number";card.inputMode="numeric";c.append(card); let code;if(p.requires_step_up){code=document.createElement("input");code.placeholder="Verification code (demo: 1234)";c.append(code)} const a=el("div","actions"),ok=el("button","","Confirm & pay"),cancel=el("button","secondary","Cancel"); ok.onclick=async()=>{try{await api("/checkout/payment-method",{session_id:state.sessionId,card_number:card.value});const r=await api("/checkout/confirm",{session_id:state.sessionId,cart_id:p.cart_id,...(code?{step_up_code:code.value}:{})});notice(r.result.outcome==="approved"?`Payment approved. Transaction ${r.result.transaction_id}.`:r.result.message||`Payment ${r.result.outcome}.`,r.result.outcome==="approved"?"success":"error")}catch(e){notice(e.message,"error")}};cancel.onclick=async()=>{try{await api("/checkout/cancel",{session_id:state.sessionId,cart_id:p.cart_id});notice("Checkout cancelled. No payment was made.")}catch(e){notice(e.message,"error")}};a.append(ok,cancel);c.append(a);thread.append(c); }
  function draw(i) { if(i.type==="text") thread.append(el("div","message",i.text)); else if(i.type==="transaction_preview") preview(i.preview); else {const row=el("div","carousel");i.products.forEach(p=>{const c=el("article","card product"),im=p.image_url?document.createElement("img"):el("div","fallback","👟");if(p.image_url){im.src=p.image_url;im.alt=p.name;im.onerror=()=>im.replaceWith(el("div","fallback","👟"))}const b=el("div","body");b.append(el("div","name",p.name),el("div","price",cash.format(p.price)));const add=el("button","","Add to cart");add.onclick=()=>chat({kind:"action",action:"add_to_cart",product_id:p.product_id,quantity:1});b.append(add);c.append(im,b);row.append(c)});thread.append(row)}scroll(); }
  state.messages.forEach(x=>x.sender==="user"?thread.append(el("div","message user",x.item.text)):draw(x.item));
  form.onsubmit=e=>{e.preventDefault();const text=input.value.trim();if(!text)return;input.value="";const item={type:"text",text};state.messages.push({sender:"user",item});save();thread.append(el("div","message user",text));scroll();chat({kind:"text",text})};
})();
